### ISSUE TITLE
Error in Julia when running include(./src/Jexpresso.jl)

### ISSUE THREAD

**Issue by fernikalo** [smarras79/jexpresso#33]
After cloning the repo, and using Julia 1.8.5, I followed the instructions in the README.md, namely >> cd $JEXPRESSO_HOME
>> julia --project=. -e "using Pkg; Pkg.instantiate(); Pkg.API.precompile()". 
In Julia I run: push!(empty!(ARGS), "AdvDiff", "case1"); without problems.
But running the command include(./src/Jexpresso.jl) produces an error:
<img width="1440" alt="image" src="https://github.com/smarras79/jexpresso/assets/35708166/4f545ea1-0a43-401f-b559-ec9582e7ab57">
Any help on that?
Thanks Simone!
Fernando

**Comment by smarras79** [comment]
that's because you are not using the `"..."` in the include string.
