### ISSUE TITLE
CompEuler3d example fails on Linux with CUDA

### ISSUE THREAD

**Issue by jennyfothergill** [smarras79/Jexpresso#51]
I am running Jexpresso commit (bb3c42d) on Centos 7, Julia 1.10.5 with V100 GPU with driver version 545.23.08 and CUDA version 12.3. My installation is as follows:
```
cd Jexpresso
sed -i '/Metal/d' ./Project.toml  # I found I needed to remove the Metal dependency on Linux to get the build to succeed
julia --project=.
]
add CUDA
instantiate
precompile
```

When I run the 3d Comp Euler example:
```
julia> push!(empty!(ARGS), "CompEuler", "3d");
julia> include("./src/Jexpresso.jl")
```
I get the following error:
```
ERROR: LoadError: UndefVarError: `update_p_ref_theta` not defined
```

**Comment by smarras79** [comment]
hi @jennyfothergill yes, we created this bug after merging of two branches. we are on this fix now.

**Comment by smarras79** [comment]
Fixed.

**Comment by jennyfothergill** [comment]
Thank you! I have verified this is working on my system.
